### ISSUE TITLE
I can't run the cache-server locally (Redis database connection error)

### ISSUE THREAD

**Issue by syedmuhammaddanish** [energywebfoundation/iam-contracts#114]
Hi, I am trying to run the iam-cache-server locally (without docker), and everything runs smoothly until I get the error "Unable to connect to the database. Retrying (1), Connection terminated due to connection timeout". 

Also this error is shown in the end. 

errno: -3008,
code: 'ENOTFOUND', 
syscall: 'getaddrinfo', 
hostname: 'redis'

Can you please help in out in resolving the issue. Thank you.
![issue1](https://user-images.githubusercontent.com/90153165/155896181-ec4aed38-eb26-43b7-b982-327b0f20c502.JPG)

**Comment by jrhender** [comment]
Hi @syedmuhammaddanish , can you post this issue in https://github.com/energywebfoundation/ssi-hub please?

**Comment by syedmuhammaddanish** [comment]
Oh sorry. I will post it there. Thanks
